name: Run the app and test it 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm' 

    - name: Install dependencies
      run: npm install

    - name: Run the app
      run: npm run start
    
    - name: Run the tests
      run: npm test
